name: Atualizar Relatorio Saude
on:
  schedule:
    - cron: '0 11 * * *' # 08:00 no horário de Brasília (UTC-3)
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar Codigo
        uses: actions/checkout@v4

      - name: 2. Instalar R (O Motor)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: 3. Instalar Quarto e TinyTeX (O Gerador de PDF)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true 

      - name: 3.1. Instalar Dependências do Sistema (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libfontconfig1-dev libfreetype6-dev pkg-config libharfbuzz-dev libfribidi-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: 4. Instalar Bibliotecas (A Ferramenta)
        run: |
          Rscript -e 'install.packages(c("tidyverse", "scales", "janitor"))'

      - name: 5. Renderizar PDF
        run: quarto render Projeto_saude.qmd --to pdf

      - name: 6. Salvar e Atualizar no Git
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Relatório Atualizado Automaticamente [Robô]"
          file_pattern: '*.pdf'

      - name: 7. Enviar por E-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Relatório de Saúde Atualizado
          to: eng.amb.prof.marcos@gmail.com
          from: Robô de Dados <eng.amb.prof.marcos@gmail.com>
          body: |
            O relatório foi atualizado.
            Segue anexo.
          attachments: Projeto_saude.pdf