name: Atualizar Relatorio Saude
on:
  schedule:
    - cron: '0 11 * * *' # 08:00 no horário de Brasília (UTC-3)
  push:
    branches: [main]
  workflow_dispatch: # Adiciona botão para teste manual
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar Codigo
        uses: actions/checkout@v4

      - name: 2. Instalar R (O Motor)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: 3. Instalar Quarto e TinyTeX (O Gerador de PDF)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true 

      # --- NOVO PASSO ADICIONADO AQUI ---
      # Explicação Lógica: O Linux do GitHub vem "vazio". Para o R conseguir
      # instalar (compilar) o Tidyverse, ele precisa dessas livrarias de sistema
      # para lidar com criptografia (ssl), download (curl) e fontes/texto (harfbuzz/fribidi).
      - name: 3.1. Instalar Dependências do Sistema (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libfontconfig1-dev libfreetype6-dev pkg-config libharfbuzz-dev libfribidi-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: 4. Instalar Bibliotecas (A Ferramenta)
        run: |
          Rscript -e 'install.packages(c("tidyverse", "scales", "janitor"))'

      - name: 5. Renderizar PDF
        run: quarto render Projeto_saude.qmd --to pdf

      - name: 6. Salvar e Atualizar no Git
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Relatório Atualizado Automaticamente [Robô]"
          file_pattern: '*.pdf' # Só comita se for PDF
          
      - name: 7. Enviar por E-mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Configurações do Servidor (Gmail)
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          
          # Credenciais (Pegando do Cofre que criamos)
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          
          # Detalhes do E-mail
          subject: Relatório de Saúde Atualizado - ${{ github.run_number }}
          to: seu_email@gmail.com, email_do_chefe@prefeitura.gov.br # Separe por vírgula
          from: Robô de Dados <eng.amb.prof.marcos@gmail.com>
          body: |
            Olá!
            
            O relatório de saúde foi atualizado automaticamente com os dados mais recentes.
            Segue o PDF em anexo para análise.
            
            Atenciosamente,
            Marcos Tomazini - Comissão Estatística.
            
          # O Arquivo para Anexar
          attachments: Projeto_saude.pdf

